name: cron

on:
  schedule:
    - cron: "0 * * * *"

env:
  APP_COOKIE: ${{ secrets.APP_COOKIE }}
  APP_IFTTT_EVENT_NAME: ${{ secrets.APP_IFTTT_EVENT_NAME }}
  APP_IFTTT_SERVICE_KEY: ${{ secrets.APP_IFTTT_SERVICE_KEY }}
  APP_MINDB_TOKEN: ${{ secrets.APP_MINDB_TOKEN }}
  APP_MINDB_URL: ${{ secrets.APP_MINDB_URL }}
  APP_MINDB_ATOM_ID: ${{ secrets.APP_MINDB_ATOM_ID }} 
  APP_MINDB_ORIGIN: ${{ secrets.APP_MINDB_ORIGIN }}

jobs:
  hourly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          node-version: 16.x
      - name: Install
        run: |
          yarn
      - name: execute
        run: |
          yarn start
